/* Unified stages, theme/language state and real workshop assignment workflow. */
(()=>{
const LANGS={ru:['ru','RU'],uz:['uz','UZ'],en:['gb','EN']};
const STAGES={
 'Оптика':['Заказ создан','Комплектация','Обработка линз','Сборка','Контроль качества','Готов','Выдан'],
 'Слух':['Заказ создан','Диагностика','Комплектация','Настройка','Контроль качества','Готов','Выдан'],
 'Протезирование':['Заказ создан','Мерки','Изготовление','Примерка','Корректировка','Контроль качества','Готов','Выдан'],
 'Ортопедия':['Заказ создан','Мерки','Изготовление','Примерка','Контроль качества','Готов','Выдан'],
 'Медтехника':['Заказ создан','Комплектация','Проверка','Настройка','Контроль качества','Готов','Выдан']
};
const STAGE_CODES={'Заказ создан':'created','Комплектация':'picking','Обработка линз':'lens_processing','Сборка':'assembly','Контроль качества':'quality_control','Готов':'ready','Выдан':'issued','Диагностика':'diagnostics','Настройка':'setup','Мерки':'measurements','Изготовление':'fabrication','Примерка':'fitting','Корректировка':'adjustment','Проверка':'inspection'};
const MASTERS=[
 {name:'Тимур Алимов',directions:['Оптика','Ортопедия']},{name:'Данияр Ким',directions:['Слух']},
 {name:'Сергей Ли',directions:['Протезирование','Медтехника']},{name:'Ильхом Усманов',directions:['Медтехника','Ортопедия']}
];
const e=s=>escapeHtml(String(s??''));
const locale=()=>state.preferences?.language in LANGS?state.preferences.language:'ru';
const tr=(key,params)=>window.MedicaI18n.t(key,params);
const sourceText=new WeakMap(),sourceAttr=new WeakMap();
const fallbackHits=new Set();
function uiText(value){const trim=String(value).trim(),keys=window.MEDICA_LEGACY_KEYS||{};if(!trim)return value;let translated=keys[trim]?tr(keys[trim]):trim;if(!keys[trim])Object.keys(keys).sort((a,b)=>b.length-a.length).forEach(source=>{if(source.length<3||!translated.includes(source))return;const escaped=source.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'),pattern=new RegExp(`(?<![\\p{L}\\p{N}])${escaped}(?![\\p{L}\\p{N}])`,'gu');translated=translated.replace(pattern,tr(keys[source]))});if(translated!==trim){fallbackHits.add(trim);console.warn(`[i18n] Legacy DOM fallback used: ${trim}`)}return String(value).replace(trim,translated)}
function applyExplicitTranslations(root=document){
 root.querySelectorAll?.('[data-i18n]').forEach(node=>node.textContent=tr(node.dataset.i18n));
 for(const [attribute,dataAttribute] of [['placeholder','i18nPlaceholder'],['title','i18nTitle'],['aria-label','i18nAriaLabel']])root.querySelectorAll?.(`[data-${dataAttribute.replace(/[A-Z]/g,m=>'-'+m.toLowerCase())}]`).forEach(node=>node.setAttribute(attribute,tr(node.dataset[dataAttribute])));
}
function localizeDOM(root=document){
 applyExplicitTranslations(root);
 const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);let node;while(node=walker.nextNode()){if(node.parentElement?.closest('script,style')||!/[А-Яа-яЁё]/.test(sourceText.get(node)||node.nodeValue))continue;if(!sourceText.has(node))sourceText.set(node,node.nodeValue);node.nodeValue=locale()==='ru'?sourceText.get(node):uiText(sourceText.get(node))}
 root.querySelectorAll?.('[placeholder],[title],[aria-label]').forEach(el=>['placeholder','title','aria-label'].forEach(attr=>{if(!el.hasAttribute(attr))return;let originals=sourceAttr.get(el);if(!originals){originals={};sourceAttr.set(el,originals)}if(!(attr in originals))originals[attr]=el.getAttribute(attr);el.setAttribute(attr,locale()==='ru'?originals[attr]:uiText(originals[attr]))}))
}
const stageName=x=>tr(`stage.${STAGE_CODES[x]||x}`);
const paymentName=value=>({'Остаток 44 600 сум':'dashboard.balance_amount','Рассрочка · оплачено 12 млн':'dashboard.installment_paid','Счёт выставлен':'dashboard.invoice_issued'}[value]?tr({'Остаток 44 600 сум':'dashboard.balance_amount','Рассрочка · оплачено 12 млн':'dashboard.installment_paid','Счёт выставлен':'dashboard.invoice_issued'}[value]):value);
const stagesFor=o=>STAGES[o.direction]||STAGES['Оптика'];
function normalize(o){
 const stages=stagesFor(o);let index=Number.isInteger(o.stageIndex)?o.stageIndex:stages.findIndex(s=>String(o.stage||'').toLowerCase().includes(s.toLowerCase()));
 if(index<0) index=o.status==='Выдан'?stages.length-1:o.status==='Готов'?stages.length-2:Math.max(0,Math.round((Number(o.progress)||0)/100*(stages.length-1)));
 o.stageIndex=Math.min(index,stages.length-1);o.stage=stages[o.stageIndex];o.progress=Math.round(o.stageIndex/(stages.length-1)*100);return o;
}
state.orders.forEach(normalize);save('orders',state.orders);
window.orderStagePercent=o=>normalize(o).progress;
window.formatMoney=v=>window.MedicaI18n.formatCurrency(v);
window.formatDate=v=>window.MedicaI18n.formatDate(v);
function stageBar(o){normalize(o);const stages=stagesFor(o);return `<div class="stage-progress"><div class="stage-track" style="--stage-count:${stages.length}" aria-label="${e(tr('workshop.current'))}: ${e(stageName(o.stage))}">${stages.map((s,i)=>`<span class="stage ${i<o.stageIndex?'done':i===o.stageIndex?'current':''}" title="${e(stageName(s))}">${e(stageName(s))}</span>`).join('')}</div><strong class="stage-percent">${o.progress}%</strong></div>`}
window.workshopCard=function(o,index){
 normalize(o);const attention=o.status==='Требует обеспечения'||o.priority==='Срочный',s=statusView[o.status]||statusView['В работе'];
 const branch=o.branch||(index%2?'Медцентр Самарканд':'Медцентр Юнусабад');
 const assignee=o.master&&o.master!=='Не назначен'?o.master:o.responsible&&o.responsible!=='Не назначен'?o.responsible:tr('common.unassigned');
 return `<article class="workshop-card card ${attention?'needs-attention':''}" data-work-item><header><div class="workshop-order"><span class="tag">${e(MedicaI18n.system('direction',o.direction||'Оптика'))}</span><b>№ ${o.id}</b><span class="status ${s[0]}">${e(MedicaI18n.system('status',o.status))}</span></div><span class="priority ${attention?'high':''}">${tr(attention?'priority.urgent':'priority.normal')}</span></header><div class="workshop-title"><div><h3>${e(o.product||tr('production.custom_order'))}</h3><p>${e(o.client)} · ${e(o.phone)}</p></div><div class="deadline"><small>${tr('common.deadline')}</small><b>${e(o.deadline)}</b></div></div><div class="workshop-core"><span><small>${tr('workshop.current')}</small><b>${e(stageName(o.stage))}</b></span><span><small>${tr('workshop.assignee')}</small><b>${e(assignee)}</b></span><span><small>${tr('workshop.branch')}</small><b>${e(branch)}</b></span><span><small>${tr('workshop.payment')}</small><b>${e(paymentName(o.payment))}</b></span></div>${stageBar(o)}<details><summary>${tr('workshop.details')} <span>＋</span></summary><div class="workshop-history">${(o.workHistory||[]).map((x,i)=>`<p>${i+1}. ${e(x)}</p>`).join('')}</div></details><footer><button class="secondary" data-open-work-order="${o.id}">${tr('workshop.open')}</button><button class="secondary" data-assign-master="${o.id}">${tr('workshop.assign')}</button><button class="primary" data-stage-advance="${o.id}" ${o.stageIndex>=stagesFor(o).length-1?'disabled':''}>${o.status==='Готов'?tr('workshop.issue'):tr('workshop.advance')}</button></footer></article>`;
};
function refresh(){applyPreferences();renderLanguage();if(currentPage!=='dashboard')renderModule();else syncDashboard();applyExplicitTranslations();localizeDOM();document.documentElement.classList.remove('i18n-pending')}
function closeLanguageMenu(){const menu=$('#languageMenu'),button=$('#languageCurrent');menu.classList.remove('open');button.setAttribute('aria-expanded','false')}
function setLanguage(lang){if(!LANGS[lang])lang='ru';state.preferences.language=lang;save('preferences',state.preferences);document.documentElement.lang=lang;refresh();closeLanguageMenu()}
function renderLanguage(){const lang=locale(),markup=v=>`<span class="language-flag flag-${v[0]}" aria-hidden="true"></span><span class="language-code">${v[1]}</span>`;$('#languageCurrent').innerHTML=markup(LANGS[lang]);$('#languageCurrent').setAttribute('aria-label',`Language: ${LANGS[lang][1]}`);$('#languageOptions').innerHTML=Object.entries(LANGS).filter(([k])=>k!==lang).map(([k,v])=>`<button role="option" aria-selected="false" data-lang="${k}">${markup(v)}</button>`).join('');$$('[data-lang]').forEach(b=>b.onclick=e=>{e.stopPropagation();setLanguage(b.dataset.lang)})}
window.setMedicaLanguage=setLanguage;$('#languageCurrent').onclick=e=>{e.stopPropagation();const m=$('#languageMenu'),open=m.classList.toggle('open');e.currentTarget.setAttribute('aria-expanded',String(open));if(open)$('#languageOptions button')?.focus()};document.addEventListener('click',closeLanguageMenu);document.addEventListener('keydown',e=>{if(e.key==='Escape'&&$('#languageMenu').classList.contains('open')){closeLanguageMenu();$('#languageCurrent').focus()}});
document.addEventListener('change',e=>{if(e.target.matches('[data-setting="language"]'))setLanguage(e.target.value)});
function assignMaster(id){const o=state.orders.find(x=>x.id===+id),eligible=MASTERS.filter(m=>m.directions.includes(o.direction)),form=$('#entityForm');entityDialog.dataset.mode='workshop-master';$('#entityEyebrow').textContent=tr('master.specialty');$('#entityTitle').textContent=tr('master.title');$('#entityFields').innerHTML=`<div class="master-grid full">${eligible.map((m,i)=>{const load=state.orders.filter(x=>(x.master||x.responsible)===m.name&&x.status!=='Выдан').length;return `<label class="master-option"><span><b>${e(m.name)}</b><small>${tr('master.specialty')}: ${e(m.directions.join(', '))}</small></span><span>${tr('master.load')}: <b>${load}</b></span><input type="radio" name="master" value="${e(m.name)}" ${i?'':'checked'}></label>`}).join('')}</div>`;form.onsubmit=ev=>{ev.preventDefault();const v=Object.fromEntries(new FormData(form)),previous=o.master||o.responsible||'Не назначен';o.master=v.master;o.responsible=v.master;o.assignmentHistory??=[];o.assignmentHistory.unshift({at:new Date().toISOString(),from:previous,to:v.master});o.workHistory??=[];o.workHistory.unshift(`Передача: ${previous} → ${v.master}`);save('orders',state.orders);entityDialog.close();renderModule();syncDashboard();notify(`${v.master} · №${o.id}`)};entityDialog.showModal()}
function openWorkOrder(id){const o=state.orders.find(x=>x.id===+id);$('#detailTitle').textContent=`№ ${o.id} · ${o.client}`;$('#detailContent').innerHTML=`${stageBar(o)}<div class="detail-list"><div><small>${tr('workshop.current')}</small><strong>${e(stageName(o.stage))}</strong></div><div><small>${tr('workshop.assignee')}</small><strong>${e(o.master||o.responsible)}</strong></div><div><small>${tr('workshop.payment')}</small><strong>${e(o.payment)}</strong></div><div><small>${tr('workshop.branch')}</small><strong>${e(o.branch||'—')}</strong></div></div><div class="patient-timeline">${(o.workHistory||[]).map(x=>`<article><b>${e(x)}</b></article>`).join('')}</div>${o.status!=='Отменён'&&o.status!=='Выдан'?`<div class="item-actions"><button class="secondary danger-text" data-cancel-order="${o.id}">Отменить заказ и освободить резерв</button></div>`:''}`;detailDialog.showModal()}

/* Real order builder: database client, line items, specialty fields and stock reservation. */
let draft;
const SPECIALTY={
 'Оптика':[['prescription','Рецепт / назначение'],['od','Параметры OD'],['os','Параметры OS'],['pd','Межзрачковое расстояние (PD)'],['frame','Параметры оправы'],['lenses','Параметры линз']],
 'Слух':[['audiogram','Аудиограмма'],['ear','Сторона / ухо'],['deviceModel','Модель устройства'],['fitting','Параметры настройки'],['earmold','Тип вкладыша']],
 'Протезирование':[['side','Сторона'],['amputationLevel','Уровень ампутации'],['measurements','Мерки'],['materials','Материалы'],['socket','Тип гильзы'],['fittingDates','Даты примерок']],
 'Ортопедия':[['diagnosis','Диагноз / назначение'],['scan','Скан / слепок'],['sizes','Размеры'],['material','Материал'],['productType','Тип изделия']],
 'Медтехника':[['medicalOrder','Назначение врача'],['delivery','Доставка'],['installation','Установка и пусконаладка'],['training','Обучение клиента'],['maintenance','Последующее обслуживание']]
};
function emptyLine(){return {type:'Товар',productId:state.catalog[0]?.id||'',name:state.catalog[0]?.name||'',qty:1,price:Number(state.catalog[0]?.price||0),discount:0,serialId:''}}
function reservedQty(productId){return state.orders.filter(o=>!['Отменён','Выдан','Черновик'].includes(o.status)).flatMap(o=>o.reservations||[]).filter(r=>r.productId==productId&&r.status==='Зарезервировано').reduce((sum,r)=>sum+Number(r.qty||0),0)}
function freeStock(product){return Math.max(0,Number(product?.stock||0)-reservedQty(product?.id))}
function totals(){const gross=draft.items.reduce((s,x)=>s+x.qty*x.price,0),discount=draft.items.reduce((s,x)=>s+x.qty*x.price*x.discount/100,0),total=Math.max(0,gross-discount),minimum=Math.ceil(total*.3),advance=Math.min(total,Math.max(0,Number(draft.advance||0)));return {gross,discount,total,minimum,advance,balance:total-advance}}
function templateLine(type,name,category){if(type!=='Товар')return {type,name,productId:'',qty:1,price:0,discount:0,serialId:''};const p=state.catalog.find(x=>x.category===category)||state.catalog.find(x=>Number(x.stock)>0)||state.catalog[0];return {type:'Товар',productId:p?.id||'',name:p?.name||name,qty:1,price:Number(p?.price||0),discount:0,serialId:''}}
const ORDER_TEMPLATES=[
 {name:'Прогрессивные очки',direction:'Оптика',items:[templateLine('Товар','Оправа','Оправа'),templateLine('Товар','Линзы','Линза'),templateLine('Работа','Работа мастера'),templateLine('Услуга','Контроль качества')]},
 {name:'Подбор слухового аппарата',direction:'Слух',items:[templateLine('Услуга','Диагностика'),templateLine('Товар','Слуховой аппарат','Слуховой аппарат'),templateLine('Работа','Настройка'),templateLine('Услуга','Обучение клиента'),templateLine('Услуга','Контрольный визит')]},
 {name:'Индивидуальное ортопедическое изделие',direction:'Ортопедия',items:[templateLine('Услуга','Сканирование'),templateLine('Товар','Материал','Ортопедия'),templateLine('Работа','Изготовление'),templateLine('Услуга','Примерка'),templateLine('Услуга','Контроль качества')]}
];
function chooseOrderTemplate(){const answer=prompt(`Выберите шаблон:\n${ORDER_TEMPLATES.map((x,i)=>`${i+1}. ${x.name}`).join('\n')}`,'1');if(answer===null)return;const item=ORDER_TEMPLATES[Number(answer)-1];if(!item)return notify('Шаблон не выбран');const conflicts=draft.items.length>1||draft.items.some(x=>x.name!==state.catalog[0]?.name);if(!confirm(`${item.name}\n\nБудут заполнены: направление и ${item.items.length} строк товаров, услуг и работ.${conflicts?'\nТекущие строки будут заменены.':''}`))return;draft.direction=item.direction;draft.params={};draft.items=item.items.map(x=>({...x}));renderOrderBuilder();notify('Шаблон подготовлен. Проверьте заказ перед сохранением')}
function repeatOrderDraft(){const previous=state.orders.find(x=>x.clientId===+draft.clientId&&x.status!=='Черновик');if(!previous)return notify('У клиента нет предыдущего заказа');if(!confirm(`Создать новый черновик на основе заказа №${previous.id}?\nПлатежи, серийные номера, резервы и ОТК скопированы не будут.`))return;draft.direction=previous.direction;draft.params={...(previous.params||{})};draft.items=(previous.items||[]).map(x=>({...x,serialId:''}));draft.advance=0;draft.paymentMethod='';renderOrderBuilder();notify('Новый черновик подготовлен из предыдущего заказа')}
function fillOrderFromLinked(){const rx=state.prescriptions?.find(x=>x.clientId===+draft.clientId);if(!rx)return notify('У клиента нет связанного рецепта');if(!confirm(`Заполнить параметры из рецепта ${rx.number}?\nКлиентские значения не будут подтверждены автоматически.`))return;draft.direction='Оптика';draft.params={prescription:rx.number,pd:rx.pd||'',frame:''};renderOrderBuilder();notify('Связанный рецепт подставлен. Проверьте параметры')}
function renderOrderBuilder(){
 const t=totals(),section=$('#orderDialog .form-section');
 section.innerHTML=`<div class="order-builder"><div class="form-tools"><button type="button" data-order-template>Выбрать шаблон</button><button type="button" data-order-repeat ${draft.clientId?'':'disabled'}>Повторить предыдущую запись</button><button type="button" data-order-linked ${draft.clientId?'':'disabled'}>Заполнить из связанной записи</button><button type="button" data-order-clear>Очистить форму</button></div><div class="form-grid"><label class="full">Клиент из базы<select data-order-client required><option value="">Выберите клиента</option>${state.clients.map(c=>`<option value="${c.id}" ${c.id==draft.clientId?'selected':''}>${e(c.name)} · ${e(c.phone)}</option>`).join('')}</select></label><label>Направление<select data-order-direction>${Object.keys(SPECIALTY).map(x=>`<option ${x===draft.direction?'selected':''}>${e(x)}</option>`).join('')}</select></label><label>Срок выполнения<input data-order-deadline type="date" value="${e(draft.deadline)}" required></label>${SPECIALTY[draft.direction].map(([k,l])=>`<label>${e(l)}<input data-specialty="${k}" value="${e(draft.params[k]||'')}"></label>`).join('')}</div><div class="order-lines-head"><h3>Товары, услуги и работы</h3><button type="button" class="secondary" data-add-line>＋ Добавить строку</button></div><div class="order-edit-lines">${draft.items.map((x,i)=>lineEditor(x,i)).join('')}</div><div class="order-calculation"><div><small>Начислено</small><b>${formatMoney(t.gross)}</b></div><div><small>Скидка</small><b>− ${formatMoney(t.discount)}</b></div><div><small>Итого</small><b>${formatMoney(t.total)}</b></div><div><small>Минимальный платёж (30%)</small><b>${formatMoney(t.minimum)}</b></div><label>Аванс<input data-order-advance type="number" min="0" max="${t.total}" value="${draft.advance}"></label><label>Способ оплаты<select data-order-payment-method><option value="">Выберите способ</option><option>Наличные</option><option>Банковская карта</option><option>QR</option></select></label><div><small>Осталось оплатить</small><b data-order-balance>${formatMoney(t.balance)}</b></div></div><button type="button" class="secondary" data-save-order-draft>Сохранить как черновик</button><p class="form-error" data-order-error></p></div>`;
 bindOrderBuilder();
}
function lineEditor(x,i){const isGood=x.type==='Товар',product=state.catalog.find(p=>p.id==x.productId),serials=(state.serialUnits||[]).filter(s=>s.product==product?.name&&s.status==='В наличии');return `<div class="order-edit-line" data-line="${i}"><label><span>Тип позиции</span><select data-line-field="type"><option>Товар</option><option ${x.type==='Услуга'?'selected':''}>Услуга</option><option ${x.type==='Работа'?'selected':''}>Работа</option></select></label><label class="order-product"><span>${isGood?'Товар из номенклатуры':'Наименование'}</span>${isGood?`<select data-line-field="productId">${state.catalog.map(p=>`<option value="${p.id}" ${p.id==x.productId?'selected':''}>${e(p.name)} (физически: ${p.stock}, свободно: ${freeStock(p)})</option>`).join('')}</select>`:`<input data-line-field="name" value="${e(x.name)}" placeholder="Наименование">`}</label><label><span>Количество</span><input data-line-field="qty" type="number" min="1" value="${x.qty}"></label><label><span>Цена, сум</span><input data-line-field="price" type="number" min="0" value="${x.price}"></label><label><span>Скидка, %</span><input data-line-field="discount" type="number" min="0" max="100" value="${x.discount}"></label>${product?.serial?`<label><span>Серийная единица</span><select data-line-field="serialId" required><option value="">Выберите серию</option>${serials.map(s=>`<option value="${s.id}" ${s.id==x.serialId?'selected':''}>${e(s.serial)}</option>`).join('')}</select></label>`:'<span></span>'}<button type="button" class="icon-button" data-remove-line="${i}" ${draft.items.length===1?'disabled':''} aria-label="Удалить строку">×</button></div>`}
function bindOrderBuilder(){
 $('[data-order-client]').onchange=x=>{draft.clientId=+x.target.value;renderOrderBuilder()};$('[data-order-direction]').onchange=x=>{draft.direction=x.target.value;draft.params={};renderOrderBuilder()};$('[data-order-deadline]').onchange=x=>draft.deadline=x.target.value;$('[data-order-template]').onclick=chooseOrderTemplate;$('[data-order-repeat]').onclick=repeatOrderDraft;$('[data-order-linked]').onclick=fillOrderFromLinked;$('[data-order-clear]').onclick=()=>{if(confirm(tr('dialog.clear_form')))resetOrder()};
 $$('[data-specialty]').forEach(x=>x.oninput=()=>draft.params[x.dataset.specialty]=x.value);$('[data-add-line]').onclick=()=>{draft.items.push(emptyLine());renderOrderBuilder()};$$('[data-remove-line]').forEach(x=>x.onclick=()=>{draft.items.splice(+x.dataset.removeLine,1);renderOrderBuilder()});
 $$('[data-line]').forEach(row=>$$('[data-line-field]',row).forEach(control=>control.onchange=()=>{const line=draft.items[+row.dataset.line],f=control.dataset.lineField;line[f]=['qty','price','discount','productId','serialId'].includes(f)?Number(control.value):control.value;if(f==='type'){Object.assign(line,emptyLine(),{type:control.value,name:control.value==='Услуга'?'Консультация и подбор':'Работа мастера',productId:control.value==='Товар'?state.catalog[0]?.id:''})}if(f==='productId'){const p=state.catalog.find(x=>x.id==control.value);Object.assign(line,{name:p.name,price:+p.price,serialId:''})}renderOrderBuilder()}));$('[data-order-advance]').oninput=x=>{draft.advance=Number(x.target.value);renderOrderBuilder()};$('[data-order-payment-method]').value=draft.paymentMethod||'';$('[data-order-payment-method]').onchange=x=>draft.paymentMethod=x.target.value;$('[data-save-order-draft]').onclick=saveOrderDraft
}
function saveOrderDraft(){const client=state.clients.find(c=>c.id===+draft.clientId),id=Math.max(2481,...state.orders.map(x=>+x.id||0))+1,t=totals();state.orders.unshift({id,createdAt:new Date().toISOString(),clientId:client?.id||null,client:client?.name||'Клиент не выбран',phone:client?.phone||'',direction:draft.direction,deadline:draft.deadline,params:{...draft.params},items:draft.items.map(x=>({...x})),reservations:[],sum:t.total,charged:t.total,paid:0,refunded:0,payment:'Не оплачено',status:'Черновик',stageIndex:0,progress:0,responsible:'Не назначен',master:'Не назначен',workHistory:['Черновик сохранён']});save('orders',state.orders);$('#orderDialog').close();syncDashboard();go('orders');notify(`Черновик заказа №${id} сохранён`)}
function draftTouched(){return Boolean(draft?.clientId||draft?.advance||draft?.items?.length>1||draft?.items?.some((x,i)=>i&&x.name)||Object.values(draft?.params||{}).some(Boolean))}
function requestOrderClose(){if($('#orderDialog').open)$('#orderDialog').close();resetOrder()}
function resolveSupply(shortages){const plans=[];for(const shortage of shortages){const {line,product,free}=shortage,choice=prompt(`Недостаточно товара: ${product.name}\nТребуется: ${line.qty}, свободно: ${free}.\n\n1 — уменьшить количество до доступного\n2 — создать перемещение из другого филиала\n3 — создать заявку поставщику\n4 — оставить в ожидании обеспечения\n5 — вернуться к форме`,'5');if(choice==='1'){if(free<1){notify('Свободного остатка нет — выберите способ обеспечения');return false}line.qty=free;renderOrderBuilder();notify(`Количество ${product.name} уменьшено до ${free}`);return false}if(choice==='2'){const branch=prompt('Укажите филиал-источник перемещения:','Медцентр Самарканд');if(!branch?.trim())return false;const id=Date.now()+plans.length;state.invoices.unshift({id,name:`TR-${String(id).slice(-6)}`,type:'Перемещение',from:`${branch.trim()} → ${state.preferences?.salon||'Текущий филиал'}`,amount:`${line.qty-free} × ${product.name}`,status:'Черновик',orderId:'pending'});plans.push({productId:product.id,qty:line.qty-free,action:'Перемещение',documentId:id,source:branch.trim()})}else if(choice==='3'){const id=Date.now()+plans.length,supplier=product.supplier||'Основной поставщик';state.procurements??=[];state.procurements.unshift({id,number:`PO-${String(id).slice(-6)}`,productId:product.id,product:product.name,qty:line.qty-free,supplier,status:'Черновик',orderId:'pending'});plans.push({productId:product.id,qty:line.qty-free,action:'Заявка поставщику',documentId:id,supplier})}else if(choice==='4')plans.push({productId:product.id,qty:line.qty-free,action:'Ожидание обеспечения'});else return false}return plans}
resetOrder=function(){draft={clientId:'',direction:'Оптика',deadline:new Date(Date.now()+5*864e5).toISOString().slice(0,10),params:{},items:[emptyLine()],advance:0,paymentMethod:'',paymentParts:{cash:0,card:0,qr:0}};$$('.steps li').forEach((x,i)=>{x.classList.toggle('active',i===0);x.hidden=i>0});$('#nextStep').textContent='Создать и зарезервировать';renderOrderBuilder()};
$('#nextStep').onclick=()=>{
 const error=$('[data-order-error]'),client=state.clients.find(c=>c.id===+draft.clientId),t=totals();if(!client){error.textContent='Выберите существующего клиента из базы';return}if(t.advance&&!draft.paymentMethod){error.textContent='Выберите способ оплаты аванса';return}if(!draft.deadline){error.textContent='Укажите срок выполнения';return}if(!draft.items.length){error.textContent='Добавьте хотя бы одну строку';return}
 const shortages=[];for(const line of draft.items){if(line.qty<1||line.price<0){error.textContent='Проверьте количество и цену';return}if(line.type==='Товар'){const p=state.catalog.find(x=>x.id==line.productId);if(!p){error.textContent=`Товар не найден: ${line.name}`;return}const free=freeStock(p);if(free<line.qty)shortages.push({line,product:p,free});if(p.serial&&line.qty!==1){error.textContent=`Серийные товары добавляются по одной единице в строке: ${p.name}`;return}if(p.serial&&free>=line.qty&&!line.serialId){error.textContent=`Выберите серийную единицу: ${p.name}`;return}}}const supplyPlans=resolveSupply(shortages);if(supplyPlans===false)return;
 const id=Math.max(2481,...state.orders.map(x=>+x.id||0))+1,reservations=[];for(const line of draft.items.filter(x=>x.type==='Товар')){const p=state.catalog.find(x=>x.id==line.productId),qty=Math.min(line.qty,freeStock(p));if(qty>0)reservations.push({productId:p.id,qty,status:'Зарезервировано'});if(line.serialId){const s=state.serialUnits.find(x=>x.id==line.serialId);s.status='В резерве';s.client=client.name;s.events??=[];s.events.unshift([new Date().toISOString().slice(0,10),'Резервирование',`Заказ №${id}`])}}supplyPlans.forEach(plan=>{const doc=(state.invoices||[]).find(x=>x.id===plan.documentId)||(state.procurements||[]).find(x=>x.id===plan.documentId);if(doc)doc.orderId=id});
 const createdAt=new Date().toISOString(),needsSupply=supplyPlans.length>0,order={id,createdAt,clientId:client.id,client:client.name,phone:client.phone,direction:draft.direction,deadline:draft.deadline,params:draft.params,items:draft.items.map(x=>({...x})),reservations,supplyPlans,sum:t.total,charged:t.total,paid:t.advance,refunded:0,payment:t.advance?`Аванс ${formatMoney(t.advance)}`:'Не оплачено',status:needsSupply?'Требует обеспечения':'В работе',availability:needsSupply?'Ожидает обеспечения':'Зарезервировано',stageIndex:0,stage:stagesFor({direction:draft.direction})[0],progress:0,responsible:'Не назначен',master:'Не назначен',workHistory:['Заказ создан',needsSupply?'Создан план обеспечения дефицитных позиций':'Товары зарезервированы']};state.orders.unshift(order);if(t.advance&&state.payments){state.payments.unshift({id:Date.now(),date:createdAt,clientId:client.id,orderId:id,client:client.name,type:'Аванс',method:draft.paymentMethod,amount:t.advance,allocations:draft.items.map((x,i)=>({line:i,amount:Math.round(t.advance*(x.qty*x.price*(1-x.discount/100))/t.total)})),fiscal:'Ожидает оформления'});save('payments',state.payments)}client.orders=Number(client.orders||0)+1;save('orders',state.orders);save('catalog',state.catalog);save('serialUnits',state.serialUnits);save('clients',state.clients);save('invoices',state.invoices);if(state.procurements)save('procurements',state.procurements);$('#orderDialog').close();syncDashboard();go('orders');notify(`Заказ №${id} создан · ${needsSupply?'требуется обеспечение · ':''}${formatMoney(t.total)}`)
};
document.addEventListener('click',ev=>{const a=ev.target.closest('[data-stage-advance],[data-assign-master],[data-open-work-order],[data-cancel-order]');if(!a)return;
 if(a.dataset.stageAdvance){const o=state.orders.find(x=>x.id===+a.dataset.stageAdvance),stages=stagesFor(o);normalize(o);if(o.stageIndex<stages.length-1){o.stageIndex++;o.stage=stages[o.stageIndex];o.progress=Math.round(o.stageIndex/(stages.length-1)*100);o.status=o.stage==='Выдан'?'Выдан':o.stage==='Готов'?'Готов':'В работе';o.workHistory??=[];o.workHistory.unshift(`${new Date().toLocaleString(locale())} · ${o.stage}`);save('orders',state.orders);renderModule();syncDashboard();notify(`№${o.id}: ${stageName(o.stage)} · ${o.progress}%`)}}
 if(a.dataset.assignMaster)assignMaster(a.dataset.assignMaster);if(a.dataset.openWorkOrder)openWorkOrder(a.dataset.openWorkOrder);if(a.dataset.cancelOrder){const o=state.orders.find(x=>x.id===+a.dataset.cancelOrder);if(!confirm(tr('dialog.cancel_order',{number:o.id})))return;(o.reservations||[]).filter(r=>r.status==='Зарезервировано').forEach(r=>{r.status='Освобождено'});(o.items||[]).filter(x=>x.serialId).forEach(line=>{const s=state.serialUnits.find(x=>x.id==line.serialId);if(s){s.status='В наличии';s.client='—';s.events??=[];s.events.unshift([new Date().toISOString().slice(0,10),'Освобождение резерва',`Отмена заказа №${o.id}`])}});o.status='Отменён';o.workHistory??=[];o.workHistory.unshift('Заказ отменён, резервы освобождены');save('orders',state.orders);save('catalog',state.catalog);save('serialUnits',state.serialUnits);detailDialog.close();renderModule();syncDashboard();notify(`Заказ №${o.id} отменён`)}
});
$('#orderDialog header button').onclick=ev=>{ev.preventDefault();requestOrderClose()};$('#orderDialog footer [value="cancel"]').onclick=ev=>{ev.preventDefault();requestOrderClose()};$('#orderDialog').addEventListener('cancel',ev=>{ev.preventDefault();requestOrderClose()});$('#orderDialog').addEventListener('click',ev=>{if(ev.target===$('#orderDialog'))requestOrderClose()});
const renderOrderBuilderBase=renderOrderBuilder;
renderOrderBuilder=function(){renderOrderBuilderBase();const method=$('[data-order-payment-method]');if(!method)return;if(![...method.options].some(x=>x.value==='Смешанная'))method.add(new Option('Смешанная','Смешанная'));method.value=draft.paymentMethod||'';$$('[data-specialty]').forEach(input=>input.placeholder='Введите данные');if(draft.paymentMethod==='Смешанная'){draft.paymentParts??={cash:0,card:0,qr:0};const box=document.createElement('fieldset');box.className='mixed-payment';box.innerHTML=`<legend>Распределение аванса</legend>${[['cash','Наличными'],['card','Картой'],['qr','QR']].map(([key,label])=>`<label>${label}<input data-mixed-part="${key}" type="number" min="0" max="${totals().total}" step="1" value="${draft.paymentParts[key]||0}"></label>`).join('')}<strong>Внесено смешанной оплатой: <span data-mixed-total>${formatMoney(Object.values(draft.paymentParts).reduce((s,x)=>s+Number(x||0),0))}</span></strong>`;$('.order-calculation').append(box);const updateMixed=()=>{const sum=Object.values(draft.paymentParts).reduce((s,x)=>s+Number(x||0),0),total=totals().total;draft.advance=Math.min(total,sum);$('[data-order-advance]').value=draft.advance;$('[data-mixed-total]').textContent=formatMoney(sum);$('[data-order-balance]').textContent=formatMoney(Math.max(0,total-sum));$('[data-order-error]').textContent=sum>total?'Сумма смешанной оплаты не может превышать итог заказа':''};$$('[data-mixed-part]').forEach(input=>input.oninput=()=>{draft.paymentParts[input.dataset.mixedPart]=Math.max(0,Number(input.value||0));updateMixed()});updateMixed()}method.onchange=event=>{draft.paymentMethod=event.target.value;if(draft.paymentMethod==='Смешанная')draft.paymentParts??={cash:0,card:0,qr:0};renderOrderBuilder()}};
$('#nextStep').addEventListener('click',event=>{if(!draft?.advance||draft.paymentMethod!=='Смешанная')return;const total=Object.values(draft.paymentParts||{}).reduce((s,x)=>s+Number(x||0),0);if(total!==Number(draft.advance)){event.stopImmediatePropagation();event.preventDefault();$('[data-order-error]').textContent='Сумма частей смешанной оплаты должна совпадать с авансом'}},true);
$('#nextStep').addEventListener('click',()=>{if(!draft?.advance||draft.paymentMethod!=='Смешанная')return;const amount=Number(draft.advance),parts={...draft.paymentParts};queueMicrotask(()=>{const payment=state.payments?.find(x=>x.method==='Смешанная'&&x.amount===amount&&!x.parts);if(payment){payment.parts=[['Наличные',parts.cash],['Карта',parts.card],['QR',parts.qr]].map(([method,value])=>({method,amount:Number(value||0)})).filter(x=>x.amount);save('payments',state.payments)}})});
new MutationObserver(records=>{if(locale()==='ru')return;records.forEach(record=>record.addedNodes.forEach(node=>{if(node.nodeType===1)localizeDOM(node);else if(node.nodeType===3&&node.parentElement)localizeDOM(node.parentElement)}))}).observe(document.body,{childList:true,subtree:true});
window.localizeDOM=localizeDOM;window.MedicaI18n.legacyFallbackHits=fallbackHits;window.MedicaI18n.audit();localizeDOM();refresh();
})();
