/* Unified stages, theme/language state and real workshop assignment workflow. */
(()=>{
const LANGS={ru:['🇷🇺','RU'],uz:['🇺🇿','UZ'],en:['🇬🇧','EN']};
const STAGES={
 'Оптика':['Заказ создан','Комплектация','Обработка линз','Сборка','Контроль качества','Готов','Выдан'],
 'Слух':['Заказ создан','Диагностика','Комплектация','Настройка','Контроль качества','Готов','Выдан'],
 'Протезирование':['Заказ создан','Мерки','Изготовление','Примерка','Корректировка','Контроль качества','Готов','Выдан'],
 'Ортопедия':['Заказ создан','Мерки','Изготовление','Примерка','Контроль качества','Готов','Выдан'],
 'Медтехника':['Заказ создан','Комплектация','Проверка','Настройка','Контроль качества','Готов','Выдан']
};
const STAGE_I18N={
 uz:{'Заказ создан':'Buyurtma yaratildi','Комплектация':'Butlash','Обработка линз':'Linzalarni ishlash','Сборка':'Yig‘ish','Контроль качества':'Sifat nazorati','Готов':'Tayyor','Выдан':'Topshirildi','Диагностика':'Diagnostika','Настройка':'Sozlash','Мерки':'O‘lchovlar','Изготовление':'Tayyorlash','Примерка':'Sinab ko‘rish','Корректировка':'Tuzatish','Проверка':'Tekshirish'},
 en:{'Заказ создан':'Order created','Комплектация':'Picking','Обработка линз':'Lens processing','Сборка':'Assembly','Контроль качества':'Quality control','Готов':'Ready','Выдан':'Collected','Диагностика':'Diagnostics','Настройка':'Fitting & setup','Мерки':'Measurements','Изготовление':'Fabrication','Примерка':'Fitting','Корректировка':'Adjustment','Проверка':'Inspection'}
};
const MASTERS=[
 {name:'Тимур Алимов',directions:['Оптика','Ортопедия']},{name:'Данияр Ким',directions:['Слух']},
 {name:'Сергей Ли',directions:['Протезирование','Медтехника']},{name:'Ильхом Усманов',directions:['Медтехника','Ортопедия']}
];
const e=s=>escapeHtml(String(s??''));
const locale=()=>state.preferences?.language in LANGS?state.preferences.language:'ru';
const tr=(key)=>{const ru=window.MEDICA_LOCALES?.ru||{},dict=window.MEDICA_LOCALES?.[locale()]||ru;if(!(key in dict))console.warn(`[i18n] Missing ${locale()}: ${key}`);return dict[key]??ru[key]??key};
const stageName=x=>STAGE_I18N[locale()]?.[x]||x;
const stagesFor=o=>STAGES[o.direction]||STAGES['Оптика'];
function normalize(o){
 const stages=stagesFor(o);let index=Number.isInteger(o.stageIndex)?o.stageIndex:stages.findIndex(s=>String(o.stage||'').toLowerCase().includes(s.toLowerCase()));
 if(index<0) index=o.status==='Выдан'?stages.length-1:o.status==='Готов'?stages.length-2:Math.max(0,Math.round((Number(o.progress)||0)/100*(stages.length-1)));
 o.stageIndex=Math.min(index,stages.length-1);o.stage=stages[o.stageIndex];o.progress=Math.round(o.stageIndex/(stages.length-1)*100);return o;
}
state.orders.forEach(normalize);save('orders',state.orders);
window.orderStagePercent=o=>normalize(o).progress;
window.formatMoney=v=>new Intl.NumberFormat(locale()==='uz'?'uz-UZ':locale()==='en'?'en-GB':'ru-RU',{style:'currency',currency:'UZS',maximumFractionDigits:0}).format(Number(v||0));
window.formatDate=v=>new Intl.DateTimeFormat(locale()==='uz'?'uz-UZ':locale()==='en'?'en-GB':'ru-RU',{day:'2-digit',month:'short',year:'numeric'}).format(new Date(v));
function stageBar(o){normalize(o);const stages=stagesFor(o);return `<div class="stage-progress"><div class="stage-track" style="--stage-count:${stages.length}" aria-label="${e(tr('workshop.current'))}: ${e(stageName(o.stage))}">${stages.map((s,i)=>`<span class="stage ${i<o.stageIndex?'done':i===o.stageIndex?'current':''}" title="${e(stageName(s))}">${e(stageName(s))}</span>`).join('')}</div><strong class="stage-percent">${o.progress}%</strong></div>`}
window.workshopCard=function(o,index){
 normalize(o);const attention=o.status==='Требует обеспечения'||o.priority==='Срочный',s=statusView[o.status]||statusView['В работе'];
 const branch=o.branch||(index%2?'Медцентр Самарканд':'Медцентр Юнусабад');
 return `<article class="workshop-card card ${attention?'needs-attention':''}" data-work-item><header><div class="workshop-order"><span class="tag">${e(o.direction||'Оптика')}</span><b>№ ${o.id}</b><span class="status ${s[0]}">${e(o.status)}</span></div><span class="priority ${attention?'high':''}">${e(o.priority||'Обычный')}</span></header><div class="workshop-title"><div><h3>${e(o.product||'Индивидуальный заказ')}</h3><p>${e(o.client)} · ${e(o.phone)}</p></div><div class="deadline"><small>Срок</small><b>${e(o.deadline)}</b></div></div><div class="workshop-core"><span><small>${tr('workshop.current')}</small><b>${e(stageName(o.stage))}</b></span><span><small>${tr('workshop.assignee')}</small><b>${e(o.master&&o.master!=='Не назначен'?o.master:o.responsible||'Не назначен')}</b></span><span><small>${tr('workshop.branch')}</small><b>${e(branch)}</b></span><span><small>${tr('workshop.payment')}</small><b>${e(o.payment)}</b></span></div>${stageBar(o)}<details><summary>${tr('workshop.details')} <span>＋</span></summary><div class="workshop-history">${(o.workHistory||[]).map((x,i)=>`<p>${i+1}. ${e(x)}</p>`).join('')}</div></details><footer><button class="secondary" data-open-work-order="${o.id}">${tr('workshop.open')}</button><button class="secondary" data-assign-master="${o.id}">${tr('workshop.assign')}</button><button class="primary" data-stage-advance="${o.id}" ${o.stageIndex>=stagesFor(o).length-1?'disabled':''}>${o.status==='Готов'?tr('workshop.issue'):tr('workshop.advance')}</button></footer></article>`;
};
function refresh(){applyPreferences();document.querySelectorAll('[data-i18n]').forEach(n=>n.textContent=tr(n.dataset.i18n));renderLanguage();if(currentPage==='production')renderModule()}
function setLanguage(lang){if(!LANGS[lang])lang='ru';state.preferences.language=lang;save('preferences',state.preferences);document.documentElement.lang=lang;refresh()}
function renderLanguage(){const lang=locale(),menu=$('#languageMenu');$('#languageCurrent').innerHTML=`<span>${LANGS[lang][0]}</span> ${LANGS[lang][1]}`;$('#languageOptions').innerHTML=Object.entries(LANGS).filter(([k])=>k!==lang).map(([k,v])=>`<button role="option" data-lang="${k}">${v[0]} ${v[1]}</button>`).join('');$$('[data-lang]').forEach(b=>b.onclick=()=>{setLanguage(b.dataset.lang);menu.classList.remove('open')})}
$('#languageCurrent').onclick=e=>{e.stopPropagation();const m=$('#languageMenu'),open=m.classList.toggle('open');e.currentTarget.setAttribute('aria-expanded',String(open))};document.addEventListener('click',()=>$('#languageMenu').classList.remove('open'));
document.addEventListener('change',e=>{if(e.target.matches('[data-setting="language"]'))setLanguage(e.target.value)});
function assignMaster(id){const o=state.orders.find(x=>x.id===+id),eligible=MASTERS.filter(m=>m.directions.includes(o.direction)),form=$('#entityForm');entityDialog.dataset.mode='workshop-master';$('#entityEyebrow').textContent=tr('master.specialty');$('#entityTitle').textContent=tr('master.title');$('#entityFields').innerHTML=`<div class="master-grid full">${eligible.map((m,i)=>{const load=state.orders.filter(x=>(x.master||x.responsible)===m.name&&x.status!=='Выдан').length;return `<label class="master-option"><span><b>${e(m.name)}</b><small>${tr('master.specialty')}: ${e(m.directions.join(', '))}</small></span><span>${tr('master.load')}: <b>${load}</b></span><input type="radio" name="master" value="${e(m.name)}" ${i?'':'checked'}></label>`}).join('')}</div>`;form.onsubmit=ev=>{ev.preventDefault();const v=Object.fromEntries(new FormData(form)),previous=o.master||o.responsible||'Не назначен';o.master=v.master;o.responsible=v.master;o.assignmentHistory??=[];o.assignmentHistory.unshift({at:new Date().toISOString(),from:previous,to:v.master});o.workHistory??=[];o.workHistory.unshift(`Передача: ${previous} → ${v.master}`);save('orders',state.orders);entityDialog.close();renderModule();syncDashboard();notify(`${v.master} · №${o.id}`)};entityDialog.showModal()}
function openWorkOrder(id){const o=state.orders.find(x=>x.id===+id);$('#detailTitle').textContent=`№ ${o.id} · ${o.client}`;$('#detailContent').innerHTML=`${stageBar(o)}<div class="detail-list"><div><small>${tr('workshop.current')}</small><strong>${e(stageName(o.stage))}</strong></div><div><small>${tr('workshop.assignee')}</small><strong>${e(o.master||o.responsible)}</strong></div><div><small>${tr('workshop.payment')}</small><strong>${e(o.payment)}</strong></div><div><small>${tr('workshop.branch')}</small><strong>${e(o.branch||'—')}</strong></div></div><div class="patient-timeline">${(o.workHistory||[]).map(x=>`<article><b>${e(x)}</b></article>`).join('')}</div>${o.status!=='Отменён'&&o.status!=='Выдан'?`<div class="item-actions"><button class="secondary danger-text" data-cancel-order="${o.id}">Отменить заказ и освободить резерв</button></div>`:''}`;detailDialog.showModal()}

/* Real order builder: database client, line items, specialty fields and stock reservation. */
let draft;
const SPECIALTY={
 'Оптика':[['prescription','Рецепт / назначение'],['pd','Межзрачковое расстояние (PD)'],['frame','Параметры оправы']],
 'Слух':[['audiogram','Аудиограмма'],['ear','Сторона / ухо'],['fitting','Параметры настройки']],
 'Протезирование':[['measurements','Мерки'],['side','Сторона'],['socket','Тип гильзы']],
 'Ортопедия':[['scan','Скан / слепок'],['diagnosis','Назначение'],['material','Материал']],
 'Медтехника':[['medicalOrder','Назначение врача'],['installation','Пусконаладка'],['training','Обучение клиента']]
};
function emptyLine(){return {type:'Товар',productId:state.catalog[0]?.id||'',name:state.catalog[0]?.name||'',qty:1,price:Number(state.catalog[0]?.price||0),discount:0,serialId:''}}
function totals(){const gross=draft.items.reduce((s,x)=>s+x.qty*x.price,0),discount=draft.items.reduce((s,x)=>s+x.qty*x.price*x.discount/100,0),total=Math.max(0,gross-discount),minimum=Math.ceil(total*.3),advance=Math.min(total,Math.max(0,Number(draft.advance||0)));return {gross,discount,total,minimum,advance,balance:total-advance}}
function renderOrderBuilder(){
 const t=totals(),section=$('#orderDialog .form-section');
 section.innerHTML=`<div class="order-builder"><div class="form-grid"><label class="full">Клиент из базы<select data-order-client required><option value="">Выберите клиента</option>${state.clients.map(c=>`<option value="${c.id}" ${c.id==draft.clientId?'selected':''}>${e(c.name)} · ${e(c.phone)}</option>`).join('')}</select></label><label>Направление<select data-order-direction>${Object.keys(SPECIALTY).map(x=>`<option ${x===draft.direction?'selected':''}>${e(x)}</option>`).join('')}</select></label><label>Срок выполнения<input data-order-deadline type="date" value="${e(draft.deadline)}" required></label>${SPECIALTY[draft.direction].map(([k,l])=>`<label>${e(l)}<input data-specialty="${k}" value="${e(draft.params[k]||'')}"></label>`).join('')}</div><div class="order-lines-head"><h3>Товары, услуги и работы</h3><button type="button" class="secondary" data-add-line>＋ Добавить строку</button></div><div class="order-edit-lines">${draft.items.map((x,i)=>lineEditor(x,i)).join('')}</div><div class="order-calculation"><div><small>Начислено</small><b>${formatMoney(t.gross)}</b></div><div><small>Скидка</small><b>− ${formatMoney(t.discount)}</b></div><div><small>Итого</small><b>${formatMoney(t.total)}</b></div><div><small>Минимальный платёж (30%)</small><b>${formatMoney(t.minimum)}</b></div><label>Аванс<input data-order-advance type="number" min="0" max="${t.total}" value="${draft.advance}"></label><div><small>Осталось оплатить</small><b>${formatMoney(t.balance)}</b></div></div><p class="form-error" data-order-error></p></div>`;
 bindOrderBuilder();
}
function lineEditor(x,i){const isGood=x.type==='Товар',product=state.catalog.find(p=>p.id==x.productId),serials=(state.serialUnits||[]).filter(s=>s.product==product?.name&&s.status==='В наличии');return `<div class="order-edit-line" data-line="${i}"><select data-line-field="type"><option>Товар</option><option ${x.type==='Услуга'?'selected':''}>Услуга</option><option ${x.type==='Работа'?'selected':''}>Работа</option></select>${isGood?`<select data-line-field="productId">${state.catalog.map(p=>`<option value="${p.id}" ${p.id==x.productId?'selected':''}>${e(p.name)} · свободно ${p.stock}</option>`).join('')}</select>`:`<input data-line-field="name" value="${e(x.name)}" placeholder="Наименование">`}<input data-line-field="qty" type="number" min="1" value="${x.qty}" aria-label="Количество"><input data-line-field="price" type="number" min="0" value="${x.price}" aria-label="Цена"><input data-line-field="discount" type="number" min="0" max="100" value="${x.discount}" aria-label="Скидка, %">${product?.serial?`<select data-line-field="serialId" required><option value="">Выберите серийную единицу</option>${serials.map(s=>`<option value="${s.id}" ${s.id==x.serialId?'selected':''}>${e(s.serial)}</option>`).join('')}</select>`:'<span></span>'}<button type="button" class="icon-button" data-remove-line="${i}" ${draft.items.length===1?'disabled':''}>×</button></div>`}
function bindOrderBuilder(){
 $('[data-order-client]').onchange=x=>{draft.clientId=+x.target.value};$('[data-order-direction]').onchange=x=>{draft.direction=x.target.value;draft.params={};renderOrderBuilder()};$('[data-order-deadline]').onchange=x=>draft.deadline=x.target.value;
 $$('[data-specialty]').forEach(x=>x.oninput=()=>draft.params[x.dataset.specialty]=x.value);$('[data-add-line]').onclick=()=>{draft.items.push(emptyLine());renderOrderBuilder()};$$('[data-remove-line]').forEach(x=>x.onclick=()=>{draft.items.splice(+x.dataset.removeLine,1);renderOrderBuilder()});
 $$('[data-line]').forEach(row=>$$('[data-line-field]',row).forEach(control=>control.onchange=()=>{const line=draft.items[+row.dataset.line],f=control.dataset.lineField;line[f]=['qty','price','discount','productId','serialId'].includes(f)?Number(control.value):control.value;if(f==='type'){Object.assign(line,emptyLine(),{type:control.value,name:control.value==='Услуга'?'Консультация и подбор':'Работа мастера',productId:control.value==='Товар'?state.catalog[0]?.id:''})}if(f==='productId'){const p=state.catalog.find(x=>x.id==control.value);Object.assign(line,{name:p.name,price:+p.price,serialId:''})}renderOrderBuilder()}));$('[data-order-advance]').oninput=x=>{draft.advance=Number(x.target.value);renderOrderBuilder()}
}
resetOrder=function(){draft={clientId:'',direction:'Оптика',deadline:new Date(Date.now()+5*864e5).toISOString().slice(0,10),params:{},items:[emptyLine()],advance:0};$$('.steps li').forEach((x,i)=>{x.classList.toggle('active',i===0);x.hidden=i>0});$('#nextStep').textContent='Создать и зарезервировать';renderOrderBuilder()};
$('#nextStep').onclick=()=>{
 const error=$('[data-order-error]'),client=state.clients.find(c=>c.id===+draft.clientId),t=totals();if(!client){error.textContent='Выберите существующего клиента из базы';return}if(!draft.deadline){error.textContent='Укажите срок выполнения';return}if(!draft.items.length){error.textContent='Добавьте хотя бы одну строку';return}
 for(const line of draft.items){if(line.qty<1||line.price<0){error.textContent='Проверьте количество и цену';return}if(line.type==='Товар'){const p=state.catalog.find(x=>x.id==line.productId);if(!p||p.stock<line.qty){error.textContent=`Недостаточный свободный остаток: ${p?.name||line.name}`;return}if(p.serial&&line.qty!==1){error.textContent=`Серийные товары добавляются по одной единице в строке: ${p.name}`;return}if(p.serial&&!line.serialId){error.textContent=`Выберите серийную единицу: ${p.name}`;return}}}
 const id=Math.max(2481,...state.orders.map(x=>+x.id||0))+1,reservations=[];for(const line of draft.items.filter(x=>x.type==='Товар')){const p=state.catalog.find(x=>x.id==line.productId);p.stock-=line.qty;reservations.push({productId:p.id,qty:line.qty,status:'Зарезервировано'});if(line.serialId){const s=state.serialUnits.find(x=>x.id==line.serialId);s.status='В резерве';s.client=client.name;s.events??=[];s.events.unshift([new Date().toISOString().slice(0,10),'Резервирование',`Заказ №${id}`])}}
 const order={id,clientId:client.id,client:client.name,phone:client.phone,direction:draft.direction,deadline:draft.deadline,params:draft.params,items:draft.items.map(x=>({...x})),reservations,sum:t.total,charged:t.total,paid:t.advance,refunded:0,payment:t.advance?`Аванс ${formatMoney(t.advance)}`:'Не оплачено',status:'В работе',stageIndex:0,stage:stagesFor({direction:draft.direction})[0],progress:0,responsible:'Не назначен',master:'Не назначен',workHistory:['Заказ создан','Товары зарезервированы']};state.orders.unshift(order);if(t.advance&&state.payments){state.payments.unshift({id:Date.now(),date:new Date().toISOString(),orderId:id,client:client.name,type:'Аванс',method:'Не указан',amount:t.advance,allocations:draft.items.map((x,i)=>({line:i,amount:Math.round(t.advance*(x.qty*x.price*(1-x.discount/100))/t.total)})),fiscal:'Ожидает оформления'});save('payments',state.payments)}client.orders=Number(client.orders||0)+1;save('orders',state.orders);save('catalog',state.catalog);save('serialUnits',state.serialUnits);save('clients',state.clients);$('#orderDialog').close();syncDashboard();go('orders');notify(`Заказ №${id} создан · ${formatMoney(t.total)}`)
};
document.addEventListener('click',ev=>{const a=ev.target.closest('[data-stage-advance],[data-assign-master],[data-open-work-order],[data-cancel-order]');if(!a)return;
 if(a.dataset.stageAdvance){const o=state.orders.find(x=>x.id===+a.dataset.stageAdvance),stages=stagesFor(o);normalize(o);if(o.stageIndex<stages.length-1){o.stageIndex++;o.stage=stages[o.stageIndex];o.progress=Math.round(o.stageIndex/(stages.length-1)*100);o.status=o.stage==='Выдан'?'Выдан':o.stage==='Готов'?'Готов':'В работе';o.workHistory??=[];o.workHistory.unshift(`${new Date().toLocaleString(locale())} · ${o.stage}`);save('orders',state.orders);renderModule();syncDashboard();notify(`№${o.id}: ${stageName(o.stage)} · ${o.progress}%`)}}
 if(a.dataset.assignMaster)assignMaster(a.dataset.assignMaster);if(a.dataset.openWorkOrder)openWorkOrder(a.dataset.openWorkOrder);if(a.dataset.cancelOrder){const o=state.orders.find(x=>x.id===+a.dataset.cancelOrder);if(!confirm(`Отменить заказ №${o.id}?`))return;(o.reservations||[]).filter(r=>r.status==='Зарезервировано').forEach(r=>{const p=state.catalog.find(x=>x.id==r.productId);if(p)p.stock+=Number(r.qty||0);r.status='Освобождено'});(o.items||[]).filter(x=>x.serialId).forEach(line=>{const s=state.serialUnits.find(x=>x.id==line.serialId);if(s){s.status='В наличии';s.client='—';s.events??=[];s.events.unshift([new Date().toISOString().slice(0,10),'Освобождение резерва',`Отмена заказа №${o.id}`])}});o.status='Отменён';o.workHistory??=[];o.workHistory.unshift('Заказ отменён, резервы освобождены');save('orders',state.orders);save('catalog',state.catalog);save('serialUnits',state.serialUnits);detailDialog.close();renderModule();syncDashboard();notify(`Заказ №${o.id} отменён`)}
});
refresh();
})();
